### ISSUE TITLE
Issue with running on CentOS 7

### ISSUE THREAD

**Issue by rzeznikj** [rmind/npf#2]
The software compiles quite nicely on CentOS 7 x64, and when I began to try npfctl, it complained that it was missing /dev/npf. As I've been a fan of PF for a while (and just trying out NPF on NetBSD), I thought I'd give it a shot to see if these powerful firewalls can run on Linux as well. 

What I'm wondering is if there's a way to safely make the proper device nodes that NPF needs on CentOS; I've tried using the mknod command to manually make a node, but it seems that npfctl doesn't pick up on it.

**Comment by fatihusta** [comment]
Is there any information for this issue?
Thanks.

**Comment by rmind** [comment]
NPF in this repository is provided as a **userspace library** to be used in a bespoke application to process packets. Typically, in combination with such frameworks like [Data Plane Development Kit (DPDK)](https://www.dpdk.org/) or [netmap](https://www.freebsd.org/cgi/man.cgi?query=netmap&sektion=4). So, while it can run in userspace on Linux, there are currently no plans to port it to the Linux kernel.

I've updated the README/documentation to reflect this better. In the future, I might add more packages/components to run Linux + DPKG + NPF in certain modes (e.g. as a userspace router + firewall).

**Comment by amulpatel** [comment]
Hi,

Does it support CentOS ? or any other linux?

I did not find dnv.h for centOS and its compilation error.
I see dnv package is available for FreeBSD but not for CentOS or other Linux.

Can you please confirm of NPF is only compatible with FreeBSD?

Thanks,
Amul Patel
