### ISSUE TITLE
segmentation fault with running nf_dpdk_demo on centos 7

### ISSUE THREAD

**Issue by ZhongqiXiao** [rmind/npf#24]
Hi, I am runnig npf on Centos7 . 
The environment:
CPU:E5-2620 v3
NIC:I350 Gigabit Network Connection 1521 
Linux Kernel:4.4.15
Distribution: Centos 7.6.1810
DPDK:17.11.2
When I had compiled npf_dpdk_demo, I run it with the command `sudo ./build/npf_dpdk_demo -c1 -n1` , I got the error `[1]    23335 segmentation fault  ./npf_dpdk_demo -c 1 -n 1
`,so I used gdb to debug npf_dpdk_demo and I set the same args , the result was that:
```
Breakpoint 1, main (argc=<optimized out>, argv=<optimized out>)
    at /root/satoshi/npf/dpdk/npf_dpdk_demo.c:254
254		for (unsigned i = 0; i < (16 * 1024); i++) {
(gdb) n
255			process_packets(npf, ifp, PFIL_IN, c);
(gdb) n

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff68ff61c in malloc_consolidate () from /lib64/libc.so.6
(gdb) n
Single stepping until exit from function malloc_consolidate,
which has no line number information.
[Thread 0x7ffff7fd7980 (LWP 26480) exited]
No unwaited-for children left.
Couldn't get registers: No such process.
```
I am new to npf, and I don't know how to sovle this problem. Your help will be greatly appreciated!

**Comment by rmind** [comment]
Seems like a regression introduced after NPF was refactored to use libnv.
Fixed.
