### ISSUE TITLE
cannot open /dev/npf

### ISSUE THREAD

**Issue by ZhongqiXiao** [rmind/npf#25]
Hi, I have compiled all the lib and `npf/src` on Centos 7, and I passed all the test with the command `npftest -c /tmp/npf.nvlist -t`,but when I run `npfctl start ` I got the error `npfctl: cannot open '/dev/npf': No such file or directory`.
I don't know what  dev/npf is used for.How to sovle the problem?
Your help will be greatly appreciated!

**Comment by yazshel** [comment]
Hey @ZhongqiXiao,

I'm not an expert but AFAIK, the NPF firewall only works on NetBSD at the moment. I'm pretty sure the library and tools exist to help monitor NPF firewalls from other (e.g. Linux) systems.

While you can build the library and tools on other systems, these won't do anything without kernel support. Until someone ports the kernel module to Linux, you'll have to switch to NetBSD if you want to     enjoy NPF's magic :)

Cheers,

Timshel

**Comment by dickgoodwin** [comment]
I am trying to use npf and dpdk.  I had the same issue with npfctl trying to open /dev/npf, which doesn't exist.  Then again, npfctl is a user interface, which I can work around -- just edit /etc/npf.conf manually, and the rest ought to work ok, except that there are other issues, which I'll ask about in a different post.  Thanks

**Comment by rmind** [comment]
You can use `npfctl` with NPF-Router as a demo application, see here:
https://github.com/rmind/npf/tree/master/app
